### ISSUE TITLE
How to use the code to extract patches from both training and testing dataset?

### ISSUE THREAD

**Issue by AdiaLoveTrance** [anuragvermaknn/digital-image-analysis-sulli#1]
Hi!
Can you tell me how to run these code to extract patches from both training and testing dataset?

**Comment by anuragvermaknn** [comment]
@AdiaLoveTrance Hi I will explain, in brief, how to extract patches from training dataset. The similar can be done for testing dataset.

Assuming you have gone through [generate_patches.py ](https://github.com/anuragvermaknn/digital-image-analysis-sulli/blob/master/utils/wholeslideimages/generate_patches.py), if you go through the main function, which is the following:

`if __name__ == '__main__':
    # print("\n\n\n generate_normal_patches_from_normal_images ")
    # generate_normal_patches_from_normal_images()

    # print("\n\n\n generate_normal_patches_from_tumor_images ")
    # generate_normal_patches_from_tumor_images()
    #
    print("\n\n\n generate_tumor_patches_from_tumor_images ")
    generate_tumor_patches_from_tumor_images()
    print " Patches have been created once."`

you can comment or uncomment as per you need. 

- generate_normal_patches_from_normal_images() will extract the normal patches from **non-tumor** images from the training dataset
- generate_normal_patches_from_tumor_images() will extract the normal patches from **tumor** images from the training dataset
- generate_tumor_patches_from_tumor_images() will extract the tumor patches from **tumor** images from the training dataset



On a different note, all the configuration/properties related to the folder structure are specified in [disk_storage.py](https://github.com/anuragvermaknn/digital-image-analysis-sulli/blob/master/properties/disk_storage.py), please have a look.


Please let me know if you have any other questions.

**Comment by AdiaLoveTrance** [comment]
I got it! Thank you very much!

**Comment by anuragvermaknn** [comment]
Closing the issue
